### ISSUE TITLE
Error Translating Bluebird Promise Stacks

### ISSUE THREAD

**Issue by ijabit** [fgnass/retrace#11]
I installed bluebird so that I can get stack traces on Promise errors. Here is an example of a stack trace that it generates:
```
Error: test
    at http://localhost:8080/js/app.44ed56.js:7079:13
From previous event:
    at VueComponent.created (http://localhost:8080/js/app.44ed56.js:7078:71)
    at callHook (http://localhost:8080/js/chunk-vendors.44ed56.js:9080:21)
    at VueComponent.Vue._init (http://localhost:8080/js/chunk-vendors.44ed56.js:10778:5)
    at new VueComponent (http://localhost:8080/js/chunk-vendors.44ed56.js:10946:12)
    at createComponentInstanceForVnode (http://localhost:8080/js/chunk-vendors.44ed56.js:10465:10)
    at init (http://localhost:8080/js/chunk-vendors.44ed56.js:10286:45)
    at createComponent (http://localhost:8080/js/chunk-vendors.44ed56.js:11756:9)
    at createElm (http://localhost:8080/js/chunk-vendors.44ed56.js:11703:9)
    at createChildren (http://localhost:8080/js/chunk-vendors.44ed56.js:11830:9)
    at createElm (http://localhost:8080/js/chunk-vendors.44ed56.js:11732:9)
    at createChildren (http://localhost:8080/js/chunk-vendors.44ed56.js:11830:9)
    at createElm (http://localhost:8080/js/chunk-vendors.44ed56.js:11732:9)
    at createChildren (http://localhost:8080/js/chunk-vendors.44ed56.js:11830:9)
    at createElm (http://localhost:8080/js/chunk-vendors.44ed56.js:11732:9)
    at createChildren (http://localhost:8080/js/chunk-vendors.44ed56.js:11830:9)
    at createElm (http://localhost:8080/js/chunk-vendors.44ed56.js:11732:9)
    at VueComponent.patch [as __patch__] (http://localhost:8080/js/chunk-vendors.44ed56.js:12239:7)
    at VueComponent.Vue._update (http://localhost:8080/js/chunk-vendors.44ed56.js:8819:19)
    at VueComponent.updateComponent (http://localhost:8080/js/chunk-vendors.44ed56.js:8947:10)
```

The syntax of `at [component].[method] ([url])` seems to break this extension and make it attempt to do HTTP calls like this: `"%20(http://localhost:8080/js/chunk-vendors.2325b2.js"`

**Comment by petermikitsh** [comment]
Could you try using the `master` branch? We switched from using `stacktrace-parser` to `error-stack-parser`-- that might fix your issue. I'll have to coordinate with @fgnass on NPM releases.

**Comment by ijabit** [comment]
Yes! That fixed it. Everything is parsing now without error. Thanks!
