### ISSUE TITLE
Huge Webpack stack traces

### ISSUE THREAD

**Issue by ijabit** [fgnass/retrace#12]
When I run retrace against a Webpack produced stack trace I get a TON of nested `/webpack:` entries like this:
```
Error: error in promise handler
    at webpack:///src/views/ArtistSearch.vue.ts:90:14
    at webpack:///src/views/ArtistSearch.vue.ts:78:7
    at webpack:///webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/node_modules/vue/dist/vue.runtime.esm.js:2917:0
    at webpack:///webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/node_modules/vue/dist/vue.runtime.esm.js:4626:0
    at webpack:///webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/node_modules/vue/dist/vue.runtime.esm.js:4794:0
    at webpack:///webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/node_modules/vue/dist/vue.runtime.esm.js:4306:0
    at webpack:///webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/node_modules/vue/dist/vue.runtime.esm.js:4127:0
    at webpack:///webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/node_modules/vue/dist/vue.runtime.esm.js:5604:0
    at webpack:///webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/node_modules/vue/dist/vue.runtime.esm.js:5551:0
    at webpack:///webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/node_modules/vue/dist/vue.runtime.esm.js:5678:0
    at webpack:///webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/node_modules/vue/dist/vue.runtime.esm.js:5580:0
    at webpack:///webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/node_modules/vue/dist/vue.runtime.esm.js:5678:0
    at webpack:///webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/node_modules/vue/dist/vue.runtime.esm.js:5580:0
    at webpack:///webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/node_modules/vue/dist/vue.runtime.esm.js:5678:0
    at webpack:///webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/node_modules/vue/dist/vue.runtime.esm.js:5580:0
    at webpack:///webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/node_modules/vue/dist/vue.runtime.esm.js:5678:0
    at webpack:///webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/node_modules/vue/dist/vue.runtime.esm.js:5580:0
    at webpack:///webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/node_modules/vue/dist/vue.runtime.esm.js:6087:0
    at webpack:///webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/node_modules/vue/dist/vue.runtime.esm.js:2656:0
    at webpack:///webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/webpack:/node_modules/vue/dist/vue.runtime.esm.js:2784:0
```

For now I'm running a regex `/\/webpack:/g` to cut them out but it seems silly to keep adding the webpack text. Here's what it is after the regex:
```
Error: error in promise handler
    at webpack:///src/views/ArtistSearch.vue.ts:90:14
    at webpack:///src/views/ArtistSearch.vue.ts:78:7
    at webpack:///node_modules/vue/dist/vue.runtime.esm.js:2917:0
    at webpack:///node_modules/vue/dist/vue.runtime.esm.js:4626:0
    at webpack:///node_modules/vue/dist/vue.runtime.esm.js:4794:0
    at webpack:///node_modules/vue/dist/vue.runtime.esm.js:4306:0
    at webpack:///node_modules/vue/dist/vue.runtime.esm.js:4127:0
    at webpack:///node_modules/vue/dist/vue.runtime.esm.js:5604:0
    at webpack:///node_modules/vue/dist/vue.runtime.esm.js:5551:0
    at webpack:///node_modules/vue/dist/vue.runtime.esm.js:5678:0
    at webpack:///node_modules/vue/dist/vue.runtime.esm.js:5580:0
    at webpack:///node_modules/vue/dist/vue.runtime.esm.js:5678:0
    at webpack:///node_modules/vue/dist/vue.runtime.esm.js:5580:0
    at webpack:///node_modules/vue/dist/vue.runtime.esm.js:5678:0
    at webpack:///node_modules/vue/dist/vue.runtime.esm.js:5580:0
    at webpack:///node_modules/vue/dist/vue.runtime.esm.js:5678:0
    at webpack:///node_modules/vue/dist/vue.runtime.esm.js:5580:0
    at webpack:///node_modules/vue/dist/vue.runtime.esm.js:6087:0
    at webpack:///node_modules/vue/dist/vue.runtime.esm.js:2656:0
    at webpack:///node_modules/vue/dist/vue.runtime.esm.js:2784:0
```

**Comment by petermikitsh** [comment]
To confirm, you’re using the master branch? If so, would you mind making a demo repo that reproduces the issue?

**Comment by ijabit** [comment]
Yes sir: "retrace": "github:fgnass/retrace#master"

**Comment by petermikitsh** [comment]
Could you share a demo repo? I'm using webpack with retrace, and I haven't encountered this issue.

**Comment by ijabit** [comment]
I'll try to find time to put one together. It may be because I'm using Bluebird, throwing the error inside a promise handler, and using:
```
Promise.config({
  longStackTraces: true
});
```
